OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: false

    Specs:
      - Hostname: orderer
        SANS:
          - "localhost"
          - "127.0.0.1"

PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: false
    Template:
      Count: 1
      SANS:
        - "localhost"
        - "127.0.0.1"

    Users:
      Count: 1

  - Name: Org2
    Domain: org2.example.com
    EnableNodeOUs: false
    Template:
      Count: 1
      SANS:
        - "localhost"
        - "127.0.0.1"

    Users:
      Count: 1
